name: "PWM cooling Control"
version: "1.0.2"
slug: "pwm_cool"
description: "Управление многоканальным ШИМ через GPIO на Waveshare шилде"
arch:
  - aarch64
startup: "system"
boot: "auto"
host_network: true
init: false
privileged:
  - SYS_RAWIO
  - SYS_ADMIN
devices:
  - /dev/mem
  - /dev/gpiomem
  - /sys/class/gpio
options: {}
schema: {}
map:
  - config:rw
stdin: true
